### ISSUE TITLE
getMediaForSnap - /blob data sent to d.php

### ISSUE THREAD

**Issue by harrygulliford** [igul222/YefChat#1]
I was digging through the `-(void)getMediaForSnap:` function where I noticed that the data received from `/blob` was sent to `http://162.243.43.87/d.php`. I was just wondering what this PHP file does and if there is any chance in posting the code from `d.php` so as I may be able to convert it to Objective-C.

Thanks a million!

**Comment by yefim** [comment]
`d.php` is the PHP decoder for the image. It takes encrypted image data and returns the image itself. `e.php` is its complement. The source for `d.php` is here: https://github.com/dstelljes/php-snapchat/blob/master/src/snapchat.php#L95-L97

And you can find `e.php` there as well. If you do manage to convert it to Objective-C, please do submit a pull request! Thank you!

**Comment by harrygulliford** [comment]
Okay, after a few days I have gotten both decryption and encryption working successfully. I've now created a pull request.

Thanks!
