### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by sambudda** [igul222/YefChat#3]
I just downloaded, compiled and ran this project in Xcode 5, iOS 7. When I try to login I get this error. What am I doing wrong?

2014-02-16 23:02:43.944 Yefchat[13348:a0b] Error: Error Domain=AFNetworkingErrorDomain Code=-1011 "Request failed: client error (429)" UserInfo=0x8ae6530 {NSErrorFailingURLKey=https://feelinsonice--hrd-appspot-com-sfa0vorks4ru.runscope.net/bq/login, AFNetworkingOperationFailingURLResponseErrorKey=<NSHTTPURLResponse: 0x8dd81a0> { URL: https://feelinsonice--hrd-appspot-com-sfa0vorks4ru.runscope.net/bq/login } { status code: 429, headers {
    Connection = "keep-alive";
    "Content-Length" = 257;
    "Content-Type" = "application/json";
    Date = "Mon, 17 Feb 2014 04:02:42 GMT";
    "Runscope-Error-Code" = 50000;
    Server = "gunicorn/18.0";
} }, NSLocalizedDescription=Request failed: client error (429)}

**Comment by sambudda** [comment]
this whole project is broken as of now 2/21/14

doesn't login and doesn't download pics from snap chat

**Comment by NiNJAPiND** [comment]
In SnapchatClient.m, try delete: data[@"version"] = @"6.0.0";

**Comment by sambudda** [comment]
login works if I do this

#define USER_AGENT @"Snapchat/6.0.2 (iPhone; iOS 7.0.4; gzip)"
#define URL @"https://feelinsonice-hrd.appspot.com/bq"

and remove data version

**Comment by sambudda** [comment]
login works if I do this

#define USER_AGENT @"Snapchat/6.0.2 (iPhone; iOS 7.0.4; gzip)"
#define URL @"https://feelinsonice-hrd.appspot.com/bq"

and remove data version

**Comment by sambudda** [comment]
login works if I do this

#define USER_AGENT @"Snapchat/6.0.2 (iPhone; iOS 7.0.4; gzip)"
#define URL @"https://feelinsonice-hrd.appspot.com/bq"

and remove data version
